#服务启动端口号
server:
  port: 8082
#服务名称（服务注册到eureka名称）
spring:
  application:
    name: producer
#RabbitMQ  config begin
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: true
        prefetch: 2
      direct:
        acknowledge-mode: manual
        default-requeue-rejected: true
    publisher-confirms: true
    publisher-returns:  true

#服务注册到eureka地址
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}:0.0.1.SNAPSHOT
    hostname: producer
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/